### ISSUE TITLE
Not able to install package in CMS12 (Net5)

### ISSUE THREAD

**Issue by Vijaykumarj** [episerver/EPiServer.Labs.LinkitemProperty#2]
Hi Team,
    I am not able to install this package into my project and this project is built on CMS12 using .Net5. 
Getting **version conflict detected**. Please find the below screenshot for your reference. Please advise on this issue.

![image](https://user-images.githubusercontent.com/26544969/142387553-a550883d-e92e-4306-94bf-42087d44e3ae.png)

**Comment by barteksekula** [comment]
We haven't converted this to CMS12 yet. Stay tuned, it should be available soon either as Labs or a part of CMS-UI core product.

**Comment by Vijaykumarj** [comment]
thanks for the update @barteksekula, Please let us know once released the package. I will use this package in my project.

**Comment by kaspars-ozols** [comment]
I was able to install the latest version, but still had to reference `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` manually.

**Comment by barteksekula** [comment]
@kaspars-ozols you're right. the nuspec does not have that dependency. good catch. will fix shortly.

**Comment by barteksekula** [comment]
Fixed in https://nuget.optimizely.com/package/?id=EPiServer.Labs.LinkItemProperty&v=1.0.1

**Comment by Vijaykumarj** [comment]
Today I included this package in the NetCorePreview project and added the below snippet but it's not rendering the LinkItem in the model editor page. 
Code:
![image](https://user-images.githubusercontent.com/26544969/156634115-414114dd-9463-4009-897a-e642ce19d91a.png)

Output in CMS Page Editor:
![image](https://user-images.githubusercontent.com/26544969/156634315-2fb1dca9-4c9e-4247-8242-59b09e10ccb7.png)

Am I missing anything?

**Comment by barteksekula** [comment]
FYI: LinkItem property support will soon be included in the core product and this add-on will no longer be necessary.
