### ISSUE TITLE
Editing broken in Epi 12.6.0

### ISSUE THREAD

**Issue by Dandroid5000** [episerver/EPiServer.Labs.LinkitemProperty#6]
Hello,

Latest Epi update seems to have broken the UI / editiing experience for these links in the cms. These are the packages that we updated:

![image](https://user-images.githubusercontent.com/96799065/168004208-81e2f584-1b63-4c0d-9230-bd7124fb6c06.png)

Can you please confirm? 

Thanks
Dan

**Comment by barteksekula** [comment]
Yes, we are working on it. 12.6.0 was a huge release that changed some internal apis.

**Comment by Dandroid5000** [comment]
Ok, understood. Thanks for the update.

**Comment by Dandroid5000** [comment]
Hi @barteksekula , can you give a rough estimation on the time it might take for this to be resolved? If it's going to take more than a few days, we will need to make a decision on rolling back the Epi version or refactoring our code. 

Sorry to be asking this, but at the moment, it's blocking our content team.

Thanks again for you support. And thanks for you work on this great package!

**Comment by barteksekula** [comment]
@Dandroid5000 1.0.2 will be public tomorrow.
